"""empty message

Revision ID: e2d20b02df11
Revises: 
Create Date: 2020-04-08 17:30:22.251751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2d20b02df11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('adresse', sa.String(length=120), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_adresse'), 'profile', ['adresse'], unique=False)
    op.create_index(op.f('ix_profile_email'), 'profile', ['email'], unique=True)
    op.create_index(op.f('ix_profile_telephone'), 'profile', ['telephone'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('declaration_suspect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('descriptif', sa.Text(), nullable=True),
    sa.Column('lieu', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_declaration_suspect_lieu'), 'declaration_suspect', ['lieu'], unique=False)
    op.create_table('don',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('descriptif', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('examen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('age', sa.String(length=12), nullable=True),
    sa.Column('sexe', sa.String(length=12), nullable=True),
    sa.Column('touxrecente', sa.String(length=12), nullable=True),
    sa.Column('respirer', sa.String(length=12), nullable=True),
    sa.Column('fievreSensation', sa.String(length=12), nullable=True),
    sa.Column('fievre', sa.String(length=12), nullable=True),
    sa.Column('malGorge', sa.String(length=12), nullable=True),
    sa.Column('impossibiliteManger', sa.String(length=12), nullable=True),
    sa.Column('courbatures', sa.String(length=12), nullable=True),
    sa.Column('perteOrdorat', sa.String(length=12), nullable=True),
    sa.Column('diarrhee', sa.String(length=12), nullable=True),
    sa.Column('maladieConnu', sa.String(length=12), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_examen_age'), 'examen', ['age'], unique=False)
    op.create_index(op.f('ix_examen_courbatures'), 'examen', ['courbatures'], unique=False)
    op.create_index(op.f('ix_examen_diarrhee'), 'examen', ['diarrhee'], unique=False)
    op.create_index(op.f('ix_examen_fievre'), 'examen', ['fievre'], unique=False)
    op.create_index(op.f('ix_examen_fievreSensation'), 'examen', ['fievreSensation'], unique=False)
    op.create_index(op.f('ix_examen_impossibiliteManger'), 'examen', ['impossibiliteManger'], unique=False)
    op.create_index(op.f('ix_examen_malGorge'), 'examen', ['malGorge'], unique=False)
    op.create_index(op.f('ix_examen_maladieConnu'), 'examen', ['maladieConnu'], unique=False)
    op.create_index(op.f('ix_examen_perteOrdorat'), 'examen', ['perteOrdorat'], unique=False)
    op.create_index(op.f('ix_examen_respirer'), 'examen', ['respirer'], unique=False)
    op.create_index(op.f('ix_examen_sexe'), 'examen', ['sexe'], unique=False)
    op.create_index(op.f('ix_examen_touxrecente'), 'examen', ['touxrecente'], unique=False)
    op.create_table('savoir',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modeTransmission', sa.String(length=12), nullable=True),
    sa.Column('animalCompagnie', sa.String(length=12), nullable=True),
    sa.Column('maniereEviter', sa.String(length=12), nullable=True),
    sa.Column('personneTouche', sa.String(length=12), nullable=True),
    sa.Column('alcool', sa.String(length=12), nullable=True),
    sa.Column('traitement', sa.String(length=12), nullable=True),
    sa.Column('temps', sa.String(length=12), nullable=True),
    sa.Column('comparable', sa.String(length=12), nullable=True),
    sa.Column('climat', sa.String(length=12), nullable=True),
    sa.Column('produitsContamine', sa.String(length=12), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_savoir_alcool'), 'savoir', ['alcool'], unique=False)
    op.create_index(op.f('ix_savoir_animalCompagnie'), 'savoir', ['animalCompagnie'], unique=False)
    op.create_index(op.f('ix_savoir_climat'), 'savoir', ['climat'], unique=False)
    op.create_index(op.f('ix_savoir_comparable'), 'savoir', ['comparable'], unique=False)
    op.create_index(op.f('ix_savoir_maniereEviter'), 'savoir', ['maniereEviter'], unique=False)
    op.create_index(op.f('ix_savoir_modeTransmission'), 'savoir', ['modeTransmission'], unique=False)
    op.create_index(op.f('ix_savoir_personneTouche'), 'savoir', ['personneTouche'], unique=False)
    op.create_index(op.f('ix_savoir_produitsContamine'), 'savoir', ['produitsContamine'], unique=False)
    op.create_index(op.f('ix_savoir_temps'), 'savoir', ['temps'], unique=False)
    op.create_index(op.f('ix_savoir_traitement'), 'savoir', ['traitement'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_savoir_traitement'), table_name='savoir')
    op.drop_index(op.f('ix_savoir_temps'), table_name='savoir')
    op.drop_index(op.f('ix_savoir_produitsContamine'), table_name='savoir')
    op.drop_index(op.f('ix_savoir_personneTouche'), table_name='savoir')
    op.drop_index(op.f('ix_savoir_modeTransmission'), table_name='savoir')
    op.drop_index(op.f('ix_savoir_maniereEviter'), table_name='savoir')
    op.drop_index(op.f('ix_savoir_comparable'), table_name='savoir')
    op.drop_index(op.f('ix_savoir_climat'), table_name='savoir')
    op.drop_index(op.f('ix_savoir_animalCompagnie'), table_name='savoir')
    op.drop_index(op.f('ix_savoir_alcool'), table_name='savoir')
    op.drop_table('savoir')
    op.drop_index(op.f('ix_examen_touxrecente'), table_name='examen')
    op.drop_index(op.f('ix_examen_sexe'), table_name='examen')
    op.drop_index(op.f('ix_examen_respirer'), table_name='examen')
    op.drop_index(op.f('ix_examen_perteOrdorat'), table_name='examen')
    op.drop_index(op.f('ix_examen_maladieConnu'), table_name='examen')
    op.drop_index(op.f('ix_examen_malGorge'), table_name='examen')
    op.drop_index(op.f('ix_examen_impossibiliteManger'), table_name='examen')
    op.drop_index(op.f('ix_examen_fievreSensation'), table_name='examen')
    op.drop_index(op.f('ix_examen_fievre'), table_name='examen')
    op.drop_index(op.f('ix_examen_diarrhee'), table_name='examen')
    op.drop_index(op.f('ix_examen_courbatures'), table_name='examen')
    op.drop_index(op.f('ix_examen_age'), table_name='examen')
    op.drop_table('examen')
    op.drop_table('don')
    op.drop_index(op.f('ix_declaration_suspect_lieu'), table_name='declaration_suspect')
    op.drop_table('declaration_suspect')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_profile_telephone'), table_name='profile')
    op.drop_index(op.f('ix_profile_email'), table_name='profile')
    op.drop_index(op.f('ix_profile_adresse'), table_name='profile')
    op.drop_table('profile')
    # ### end Alembic commands ###
